### ISSUE TITLE
SponsorBlock Support?

### ISSUE THREAD

**Issue by lordfiSh** [tubearchivist/tubearchivist#119]
SponsorBlock is supported by [yt-dlp](https://github.com/yt-dlp/yt-dlp#sponsorblock-options), but I can't find any note of Support in tubearchivist. Is is possible to add?

Thanks

**Comment by bbilly1** [comment]
So the longer I've been thinking about that, the more complicated this has become:

- I've been looking on some of my subscriptions when they release a new video and depending how soon after release you are downloading, that entry might not be available yet. So just passing that option to yt-dlp will work but only depending on the timing, or when it fails it would have worked just an hour later because somebody provided timestamps by then...
- There have also been cases of vandalism where the results were wrong, so there needs to be a way to handle that too but once the video has been cut, it's cut and you'll have to download it again.
- Also this would make most sense to be able to configure on a per channel basis to avoid DDOSing a free 3rd party API for channels that don't have annoying sponsors to begin with. Right now, there is no such mechanism, to allow for per channel settings I mean, but is something I've been thinking about too...
- Also when using data from a free and open API like that, it would be a pity to not also have a mechanism to contribute to the API by providing timestamps or voting on the validity of the existing ones so this project doesn't just leech on the work of others.

So yes, I agree *in spirit*, but there are a few questions that will require an answer first. Or what are your thoughts?

**Comment by Code-Slave** [comment]
I think if some collab to get feedback from us "users" to sponsorblock would be a good idea to open up discussion with them to see if they are up for the feedback? 

Also if implemented some caveat in the setup to state something like downloading videos immediately may not have sponsorblock available due to the timeframe or similiar

**Comment by ajayyy** [comment]
Please don't worry about spamming the API if you aren't making lots of the same request for a single video.

But yea, it would probably require delaying downloading the video for some hours to ensure that there are not only some segments, but also that any bad ones have been downvoted, or a moderator has cleaned up the segments if it is a big channel.

**Comment by bbilly1** [comment]
@ajayyy Big fan of the project! :-) Thanks for your comment here. Delay the download or maybe even better, download immediately and then vote on videos that don't have any segments found yet or confirm segments that aren't locked yet. As people can now have downloads automated on a schedule, this could be a good way to contribute for these early downloaders. Then ffmpeg is already installed, so trimming the video and store the cuts made once the data becomes available would be pretty easy to do. 

In any case, I shoot you a message once I have a solution.

**Comment by Cycor** [comment]
I would vote for a chapter feature with SponsorBlock support instead of cutting the video, I would like to have an original version of the video at all times, and it could read the chapters in the video description for additional entries. You could then let the user choose which bookmarks to skip automatically (sponsor, intro, outro, selfpromo, etc)

At the moment the chrome plugins queries sponsorblock for every video you want so you could even update the data when viewing starts without really overloading the webservice.

**Comment by bbilly1** [comment]
Thanks for all the feedback. v0.1.4 now has sponsorblock implemented. Please update.
