### ISSUE TITLE
Subtitle naming convention compatibility

### ISSUE THREAD

**Issue by dfein38347g** [tubearchivist/tubearchivist#195]
The subtitles saved next to the video titles are incompatible with emby and jellyfin. They are stored with the same file name as the video with the language at the end, such as below:

Video.mp4
Video-en.vtt

According to emby documentation, the file name must match exactly and the language is specificied in the extension. https://support.emby.media/support/solutions/articles/44001159160-subtitles. See below:

Video.mp4
Video.en.vtt

I have tested this and verified that if the subtitle language is moved to the extension, it shows up in emby and jellyfin.

This app is awesome and it solves a lot of problems for me and my family. I appreciate all the developers and I hope this is a simple fix!

**Comment by bbilly1** [comment]
Hmm, yes, I wasn't considering anything like that as primary focus for now is the [web interface](https://github.com/bbilly1/tubearchivist/wiki/FAQ#2-embyplexjellyfinkodi-integrations) and not compatibility with other platforms. Changing these things are not as easy as just changing how the paths are build, because that will break compatibility for the old paths and will potentially duplicate the subtitle files when refreshing the metadata. 

I'll see what I can do.

**Comment by lamusmaser** [comment]
The file name convention is also the same for other media applications (like Plex). I could see a few possible ways to handle this:
1. Convert everything to use the Video.ll.ext naming format, with a new portion of the startup script checking to see if there are any using the Video-ll.ext and converting those to the newer naming format.
2. Add a button to the Subtitle section for "external media formatting" checkbox, which will download all newer ones with the newer naming format. This could also come with a button to "Rename all subtitle files" - Search for any subtitles, then rename any that don't match the expected format. This could work either way.
3. Setup to work with only the newer naming format, and then have a note in the changelog that existing subtitles will need to be renamed by the user.

I'd prefer if I didn't have to set a script on my side to rename all of the subtitle files every day, but I can do so. I just wouldn't want that to be something that everyone else has to do, as well.

**Comment by bbilly1** [comment]
I have made some preparations with that in a previous commit, to avoid having duplicate subtitle files with the rescan task. Just renaming them on the filesystem will break them in the interface, as the paths will be wrong, so that wouldn't work.

I think the new naming convention should only apply for new downloads and videos from the refresh task. This wouldn't break the subtitles for everybody else and wouldn't need a startup check requiring a complicated rename of the files and change for the paths in ES.

**Comment by bbilly1** [comment]
this is now published in v0.1.6, new subtitles will use the .lang.vtt filenames.
