### ISSUE TITLE
Elasticsearch version error lists a minimal version but throws errors on newer versions

### ISSUE THREAD

**Issue by agrider** [tubearchivist/tubearchivist#197]
`minial required elasticsearch version: 7.17, please update to recommended version.`

I'm receiving the above error on startup currently which causes the container to fail to start. I am however currently running the ES latest tag, which points to ES version 8.1.1, which is obviously a newer version than 7.17. I'm not sure if the error message is incorrect and the _only_ supported version is a 7.17.x version rather than the _minimum_ version being 7.17.x or if there is a bug in the startup scripts that fails to recognize the 8.x.x versions as being new enough. Just looking to confirm which is true.

**Comment by bbilly1** [comment]
Yes, that is not worded correctly. Startup script validates >=7.17 and <8.0.0, so that's not really "minimal" version... I thought ES doesn't have a latest tag, where do you get the image from?

I have fixed some depreciation warnings in this release in preparation for a future upgrade to ES 8 but I didn't had the time to go through the whole release notes yet and do some thorough testing, at first glance it looked like I need to update some queries... 

From their upgrade notes they state that v7.17 will allow for an automatic upgrade to 8 for the indexes created with 7, so I thought that would be a good opportunity to validate that now.

Have you been running ES8 the whole time without any issues?

So fixes:
- use the required ES version
- rebuild your container with the startup check disabled: https://github.com/bbilly1/tubearchivist/blob/9e37c0fab15a1fd137adc9bf0c5634c25b627317/tubearchivist/home/apps.py#L104 by removing that `sys.exit(1)` call there.

**Comment by agrider** [comment]
Sorry, in retrospect I realize my wording was pretty unclear. I'm using the official ES dockerhub image. I'm not on the `latest` tag, I'm just on the latest tag, which is `8.1.1`.  😛 

I don't know the exact date when I switched to 8.x.x from the 7.x.x tags but it _appeared_ to work correctly for me. I didn't do any serious checkout but I have archives from as recent as 3/23, which is roughly a couple of weeks after I switched, so as far as I can tell it's working fine, at least for the functions I was leveraging.

The issue with moving back to the 7.x version is that the upgrade to 8.x alters your data store and a downgrade isn't possible without data loss. I actually tried that first after getting the error from TA, but the ES container fails to start, emitting a warning that states as much. 

Personally, my suggestion would be to replace the `sys.exit` call with a print statement warning that 8.x hasn't been fully validated and to use it at your own risk until such time. That way rubes like me who upgraded already can start their container but will be aware that there may be issues and they can help to identify any bugs and open issues for them to be worked out.

**Comment by bbilly1** [comment]
Yes, I think there is a mention in the ES docs that downgrading isn't possible due to the changes how things get stored.

A print statement will be very easy to miss, these log outputs fly by very fast and if the container doesn't stop, you might not see it. 

You will be able to restore from backup, even if the backup is from a different version, as that is just json data. So I'd suggest to bash in to the container and remove the exit statement, make a backup from the latest state, then install a blank ES7 and restore the backup into this. Then you should be able to run the latest version of TA without any issues.
