### ISSUE TITLE
Feature Request: Schedule to allow changes in download speed

### ISSUE THREAD

**Issue by Marthisdil** [tubearchivist/tubearchivist#198]
For example, during the work day/evenings, I want to limit it to say, 300KB/sec.  However, starting at 10PM (after I've gone to bed and such), I'd like to uncap it (or change it to 1500KB/sec, etc) and have it be uncapped until say, 6AM the next morning.

**Comment by bbilly1** [comment]
Hmm, that could come in handy, especially with limited bandwidth and multiple users in the network.

Will need some thinking on how that input would look like, and probably will have some limitations, probably wouldn't be able to change the speed during downloading of a video, but when starting the next in the queue.

**Comment by bbilly1** [comment]
@Marthisdil Hey, it's time to join us in realizing some of your ideas! We also need people who can help develop these things.

**Comment by bt61** [comment]
I just discovered this project today, and this feature is the first thing I came looking for!  I have a very poor rural internet connection, so a primary appeal of downloading yt content is to function as a cache that fills while my household sleeps so that those videos are ready to play with no delay and without using precious bandwidth while the household is awake.  qBittorrent's implementation is great, but anything along these lines would be an excellent addition and I hope to see it remain a priority for future development.

**Comment by florensie** [comment]
As mentioned in #388, it would be a nice temporary solution to have a "stop queue schedule". Since we already have a start schedule that would allow for some basic scheduling of large download queues.

**Comment by bbilly1** [comment]
That has been sitting here for a long time, nobody wanted to take this on. Unlikely that this will been worked on anytime soon. If you really need it, feel free to implement it.

Alternatively there are other methods of bandwidth control, some router offer that functionality, a proxy container could work too, iptables offers that functionality aswell. Plus in the future config values will be exposed through the API allowing you to implement that through that as well.
