### ISSUE TITLE
Downloaded videos doesn't have original title

### ISSUE THREAD

**Issue by Doublemyst** [tubearchivist/tubearchivist#248]
Hi there

I have tried to download videos from a Food-YouTuber, but as the original title is in cyrillic, it isnt't saved.  The file names are like "20220514_HCv4xrZqsdQ_ .mp4". How can I add the full video title?
Here a video example: https://www.youtube.com/watch?v=kZ8LENKga4Q from the channel.

P.S. I didn't found any issues with the language tag search, but if there was one, please guide me to the right place :)

Thanks

**Comment by bbilly1** [comment]
File system wise, all characters are sanitized to ASCII only. This is to avoid compatibility issues of illegal characters between different fileystems. That's why you see the empty title for that video. So that is working as intended. 

But the interface should show the title correctly? At least it does for me.

Related: #127
