### ISSUE TITLE
Deleted videos should be added to the ignore list

### ISSUE THREAD

**Issue by samdoshi** [tubearchivist/tubearchivist#286]
It would be nice if videos (from subscribed channels) that have been deleted don't show up again in the download queue. Perhaps they could be added to the ignore list automatically when they are deleted?

**Comment by bbilly1** [comment]
Yeah, we had a short conversation before about that. I was a bit hesitant, if that happens automatically, you won't be able to download it again, until you go to the ignored list and delete it from there. So that could be confusing, as any ignored videos will skip without any warning even if you add it explicitly. 

But maybe there is a way how this could be done, so that it's obvious? Maybe as part of the delete confirmation? When you click on *Delete Video* you get *Delete*, *Delete and ignore* and *cancel*?

**Comment by samdoshi** [comment]
I think you've got four options:

 1. Always add it to the ignore list
 1. An option in the settings to "add deleted videos to the ignore list"
 1. Your suggestion "Delete, Delete and ignore and cancel"
 1. Similarly to your suggestion, when you click delete you get the options "Delete", "Cancel", but also a checkbox "Also add to ignore list". The state of the checkbox can be remembered between uses.

I think I would like the 2nd or 4th options.

I think with options 1 and 2, you just need to make sure that there is a message in the confirmation saying that the deleted video will be added to the ignore list as well, so that users know where to find it again.

**Comment by Joshfindit** [comment]
I would like to suggest adding a flag to the video metadata so that that flag can be used to ignore/hide in the UI.

This is related, but I actually want to be able to view all videos I have that have been removed from YouTube (and check if there are any freshly removed videos)

Something like:`removed = user_deleted|uploader_made_private|uploader_deleted`

**Comment by cmuc24** [comment]
oh nice, looks like similar to my suggested blacklist feature [last year ](https://github.com/tubearchivist/tubearchivist/discussions/110) 
thumbs up for that 👍

**Comment by SmartPhoneLover** [comment]
> I would like to suggest adding a flag to the video metadata so that that flag can be used to ignore/hide in the UI.
> 
> This is related, but I actually want to be able to view all videos I have that have been removed from YouTube (and check if there are any freshly removed videos)
> 
> Something like:`removed = user_deleted|uploader_made_private|uploader_deleted`

Maybe add both options, I mean:
- Delete / Delete & Ignore / Cancel (will free up space on disk)
- Hide / Cancel (will keep the video on disk, but it will be hidden)

Also, if both implementations are a good idea to allow the user to get rid of the selected video, I would include an option somewhere to unhide all hidden videos, at least: temporal action.

But, I like the idea to be able to ignore the video at the same time as you can delete it, because I use to download the file prior to delete it, because of my setup.

**Comment by bbilly1** [comment]
please, let's stay on topic, this feature is about ignoring deleted videos from feature downloads. the approach here makes sense to me: https://github.com/tubearchivist/tubearchivist/issues/286#issuecomment-1200098360

_somebody_ just needs to implement it.

**Comment by SmartPhoneLover** [comment]
Understood.
May I open a different issue for my special request then?

**Comment by WillScott73** [comment]
I take it no one has implemented it then, having spent a few hours deleting downloads I don't want to keep, only to see them be downloaded again. 

If TA had been written in C++, VB.Net, C# or Golang I'd have given it a go myself....

**Comment by bbilly1** [comment]
that's now shipped with v0.4.8, please update.
