### ISSUE TITLE
Missing search API endpoint

### ISSUE THREAD

**Issue by PrivateGER** [tubearchivist/tubearchivist#290]
While trying to write my own client for Tubearchivist, I noticed that there isn't any sort of API endpoint for search.

The /process/ endpoint does the job perfectly, but unfortunately requires a CSRF token and therefore does not work with token-based auth.

Can we get a search API endpoint, or allow token-auth for /process/?

**Comment by bbilly1** [comment]
Yeah, the API is under development and far from complete and [this here](https://github.com/tubearchivist/tubearchivist/tree/master/tubearchivist/api) is very much true: 
> This is very early stages and will change!  

At current state, there are quite a few things missing or only partially implemented, search being only one of them.

Did you see, there is already a good amount of progress with the NextJS/React frontend: https://github.com/tubearchivist/tubearchivist-frontend, but we stalled there, due to life but is just begging you to pickup where we left off! :-)

The `/process/` url was a *poor mans API* in the beginning, I have been moving things over to to the *real* api endpoints. 

In any case, please reach out on Discord, I'd love to hear your plans! And please help with developing the missing pieces there.

**Comment by bbilly1** [comment]
Thanks for implementing that. PR is now out in v0.2.1.
