### ISSUE TITLE
Mark all videos as watched

### ISSUE THREAD

**Issue by mmuenker** [tubearchivist/tubearchivist#296]
Is there a way to mark all videos as watched?

**Comment by SmartPhoneLover** [comment]
I think (didn't test), that the 'Mark as watched' button within the channel's page is the option you are looking for.

**Comment by bbilly1** [comment]
Yes, as mentioned, on a channel by channel basis.

To write it directly into the database you, bash into the container, and run this curl command from there:

```bash
curl -XPOST "$ES_URL/ta_video/_update_by_query?pretty" -u elastic:$ELASTIC_PASSWORD -H "Content-Type: application/json" -d '
{
  "query": {
    "match_all": {}
  },
  "script": {
    "source": "ctx._source.player.watched = true",
    "lang": "painless"
  }
}'
```

To update it all in one go. 

Hmm, do we need a button for that on the settings page? Depending on the amount of channels, you'll be clicking through things for some time otherwise...

**Comment by mmuenker** [comment]
Is there any reason not to include this feature in the user interface? I have more than 50 channels and it would be very handy to have a button to mark them all as viewed.

**Comment by bbilly1** [comment]
Well, a oneoff command that you might want to run once only, easy enough to run as a curl command if you really need to or on a per channel basis through the interface...

If you want to jmplement it, please do!
