### ISSUE TITLE
[Feature Request]: Channel/Playlist specific Scan and Queued

### ISSUE THREAD

**Issue by M4NH3X** [tubearchivist/tubearchivist#317]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations).

### Your Feature Request

**Scan:** Currently "Rescan subscriptions" option on Downloads page triggers all subscribed channel/playlist. It would be nice to have button or some sort of trigger on Channel/Playlist page themselves to start scan for new content. 
Pros: Less requests being sent to YT and more control on Scan for users.

**Queued:** Currently queued items only shown on Downloads page. It would be nice to also show them on their respective Channel/Playlist page.
Pros: It will also help in finding things fast as Downloads page can get cluttered real quick.

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
So main idea for this project is *set and forget*, this means handle things in bulk and not one by one. So that's where the focus has been so far. So this comes down to, if you or somebody wants to implement that on a per channel basis, please do and make a PR. 

To filter the downloads per channel, that could be implemented now since we split up the channel pages. 

OK, help wanted, please contribute!

**Comment by bbilly1** [comment]
We now have channel page filter implemented in v0.2.3 to easier navigate your download queue.
