### ISSUE TITLE
[Feature Request]: Search input/button on all pages (channel, playlist, downloads)

### ISSUE THREAD

**Issue by M4NH3X** [tubearchivist/tubearchivist#318]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations).

### Your Feature Request

There is dedicated Search icon which can already search everywhere as well as specific pages with filters. However, it would be really nice to have search button or input which can search on that particular page.
_Improves:_ It will improve the UX where I don't have to click on Global search, then type `channel: xyz`. Instead being on Channels page, I can just click on search button and it should start searching for channels right away.

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
Hmm, I find it much more convenient to have this all in one place instead of spread out. This is inspired from other media servers like Emby for example, which also has a unified search over all, which I find very convenient. But maybe that's just me? Please add your comments.

Also so it's obvious how the results are sorted, on the video, channel page is based on your sorting preference, on the search page is based on search relevance. 

How about, if you click on the search icon from a channel page, this will automatically prepopulate `channel:` to the form so you can just keep typing from there? But this could also be confusing, as it might not be obvious any more that you can search over the whole index without a keyword... Hmm, not sure how this could be done without being confusing.

**Comment by bbilly1** [comment]
Thanks for thinking about this but I think we'll stick with the dedicated search page as we have it now. I'm sure we'll come up with some additional improvements there.
