### ISSUE TITLE
[Installation]: VPN docker-compose setup

### ISSUE THREAD

**Issue by zero-thermo** [tubearchivist/tubearchivist#366]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux docker-compose

### Your installation or setup question

What's the correct way to put Tube Archivist behind a VPN so that YouTube does not see my public IP? 

I have WireGuard setup in a separate docker-compose file, and tried putting the `tubearchivist` front end behind a VPN with the following:

        network_mode: container:wireguard

When I do that, logs repeatedly show: `waiting for elastic search to start` and I cannot access Tube Archivist.

To add `archivist-redis` and `archivist-es` services behind the same VPN, I needed to remove the `expose` port sections in order for the compose file to successfully run. However, doing that still results in the same `waiting for elastic search to start` in the logs.    

### Relevant log output

```shell
tubearchivist logs:

    waiting for elastic search to start
    waiting for elastic search to start
```

**Comment by bbilly1** [comment]
There isn't really a *correct* way on how to do that. Some people prefer to use their router as a VPN client to tunnel their whole network, other setup the host machine where docker is running on as the VPN client to tunnel that, others use a proxy container, to only tunnel a specific container through the VPN.

That's mainly a matter of preference, your scenario and your setup, and not really about how to install this project. 

But whatever you do, the three dependent container need to be on the same network and need to be reachable by each other, otherwise you'll see the "waiting for..." message, that will eventually timeout with a connection failed.
