### ISSUE TITLE
[Feature Request]: Optionally downloading #Shorts and livestreams, and giving them their own page

### ISSUE THREAD

**Issue by pairofcrocs** [tubearchivist/tubearchivist#368]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

Adding the ability to select if shorts are downloaded or not. Also, moving the shorts out of the channel page and into their own shorts page. 
![Screenshot 2022-11-27 200815](https://user-images.githubusercontent.com/34723037/204177408-03f083e6-2df8-4785-9220-e95413758723.png)

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
Thanks for collecting that here. Some additional findings: Shorts can be extracted from the `/shorts` channel page, e.g. `https://www.youtube.com/channel/UC4JX40jDee_tINbkjycV4Sg/shorts` will return all shorts, so we can add this to ES and filter from there.

**Comment by PhuriousGeorge** [comment]
Also need to get `#livestreams` added, linked as `streams`.

Can be extracted from `/streams` channel page, e.g. `https://www.youtube.com/channel/UC4JX40jDee_tINbkjycV4Sg/streams` will return all Livestreams

Personally I find this a high-level... not issue, but broken feature due to YTs changes.

**Comment by bbilly1** [comment]
Thanks for adding that. In the meantime, as these videos have the same url, you can also add the video directly to the download queue.

**Comment by simpleman19** [comment]
I'm interested in helping to do the work to add this feature as a few of the channels that I subscribe to almost exclusively do live content which was broken in the youtube change of moving to a separate page.

I have been playing around a little bit in the codebase and have a more or less working solution but want some guidance on the best way to handle this since I am new to this codebase.

Initial question is should there be a ta_live and ta_shorts to keep lives and shorts separate from all the normal videos or just add a flag for live and short to the ta_video?

Also, at first glance it doesn't look like there are any flags coming from the youtube api to indicate short except for them coming from the "shorts" page.  I think the process is to check for a '#short' in the title or description as well as ensure <= 60 seconds in duration.

**Comment by pairofcrocs** [comment]
> 

Thanks for reaching out!

We're thinking of doing a Discord live stream soon. kind of going over the codebase to help new devs get comfortable.

If you're interested, you can see it there when we go live, otherwise, we'll be recording it too.

@bbilly1 will be able to answer your initial questions before that though.

**Comment by simpleman19** [comment]
@pairofcrocs Awesome, I will definitely tune in.  I usually don't do much with open source projects, mainly stick with my contracting work but I would really like to see this implemented so I don't mind spending a few hours knocking it out.

The codebase is pretty straightforward, I didn't have a whole lot of problems finding everything and getting a POC implemented in a couple hours just to get familiar and play with everything.

**Comment by bbilly1** [comment]
@simpleman19 were you able to make any progress on this one? Please reach on on Discord so we can coordinate to avoid making duplicate work.

**Comment by simpleman19** [comment]
Apologies for the delayed response, last week was a super busy week for me.  I will grab the discord link and reach out so we can coordinate further, I should have some time this week to burn on this.

**Comment by simpleman19** [comment]
Just opened a PR #395

**Comment by bbilly1** [comment]
This is now merged in v0.3.1. Thanks for your help with that!
