### ISSUE TITLE
[Bug]: json file bulk import too big for request

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#406]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

## Describe the bug
If the backup files get too big for some index like subtitles and comments, the bulk import request will fail. You'll have to do an awkward workaround of splitting the files and manually importing them.

This does not affect the snapshots, you should *really* use snapshots.

## Steps To Reproduce
It's unclear what the max size is, probably depends on various things like available system resources. 

## Expected behavior
Big json files should get split up into manageable chunks when creating the archive.

### Relevant log output

```shell
na
```

### Anything else?

You should really activate snapshots, particularly if you have 10k+ videos in the archive.

**Comment by Silverdutchman** [comment]
I have over 81400 video's and the upgrade from 0.3.2 to 0.3.3 or 0.3.4 get an out of memory with java Heap size (23Gb according to the output) when it's updating/migrating the subtitles. I know I am pushing the limits with this, so I don't complain about it, but for now I am stuck to version 0.3.2. 

Large collections are a problem, but as those most other software (I even had to adjust Plex database memory) because it was running too slow. But no matter how high I set java Heap size, it just fails with an out of memory and then ES and TA itself stops (Docker halt).

Again, it's not a problem for me now.

For those who are curious, I run an offsite (Ship) server that stores files locally, 12000+ movies, 3600 TV shows and Youtube 😉

**Comment by lamusmaser** [comment]
Hmm... we have several users with larger video counts, so it isn't impossible to get it to upgrade. I think the better option here is stated regarding setting up the split files OR setting up the snapshots (_you really should activate snapshots_), and that should allow it to move past.

If you would like to discuss it further, we can look into the best methodology in the Discord support channel. We'll be able to give more specific guidance and troubleshooting so that you can move off of v.0.3.2, which has the non-working yt-dlp as part of it.

**Comment by lamusmaser** [comment]
We were able to enable snapshots for @Silverdutchman and now he is up and running.

**Comment by Silverdutchman** [comment]
> We were able to enable snapshots for @Silverdutchman and now he is up and running.

I can confirm, everything is up and running

**Comment by bbilly1** [comment]
that's implemented in v0.4.2. new backups created from this version will have split json files in the zip.
