### ISSUE TITLE
[Bug]: Videos Missing & Did not acquire rescan lock.

### ISSUE THREAD

**Issue by Jay4242** [tubearchivist/tubearchivist#414]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux, Docker-Compose

## Describe the bug
After updating to v0.3.2 I have a few errors where many files aren't showing up and when rescanning subscriptions & trying to download I get 'Did not acquire rescan lock' errors.

The old videos are still on the disk even though they don't show up in TA.

I can't manage to get it to scan or download now.  

### Relevant log output

```shell
[2023-01-21 00:13:18,156: INFO/MainProcess] Task update_subscribed[61686b28-6767-4cb6-88d0-4532a4066fc3] received
[2023-01-21 00:13:18,161: WARNING/ForkPoolWorker-4] Did not acquire rescan lock.
[2023-01-21 00:13:18,162: INFO/ForkPoolWorker-4] Task update_subscribed[61686b28-6767-4cb6-88d0-4532a4066fc3] succeeded in 0.004351466996013187s: None
```

**Comment by lamusmaser** [comment]
Thank you for reporting this. We also identified this yesterday, but I had not been able to make an Issue for the problem, so thank you for providing the details.

It looks like some of the logic changed around the startup mechanisms that clears those locks. Because of this change, it is not clearing out existing locks and does not allow videos to download afterward.

We do have processes for clearing out the `redis` locks.

**Note: This should only be performed if you are seeing the "Did not acquire lock" for either rescan or download. You should be fully certain that a task is not ongoing for those activities.**
1. Login to the `redis` container. For example:
2. Activate the CLI for the DB: `redis-cli`
3. Review the keys and determine if there is a key for `ta:downloading` and/or `ta:rescan`: `KEYS *`
4. Delete only that key reference: `DEL ta:downloading` OR `DEL ta:rescan`
5. Exit out of the DB CLI and container with `exit`.
6. Attempt to run the task again and confirm that it is working.

**Again, do not run through the above steps if you are not certain that the rescan or download activities are not ongoing.**

As a note, we may identify other keys that are not getting cleared that are blocking tasks. If those come up, we will update this thread. We are also working on a PR to resolve the bug and will link this thread when that is completed, as well.

**Comment by lamusmaser** [comment]
Looking into this more, this seems to be caused by a latent lock being present for `startup_checks`. If this lock persists into a restart of the container, which can happen if the TA container is restarted at any point during the startup process between the "run startup checks" message and setting the lock to expire; the function just prior is updating the ES vid_type, which has the one or more message outputs of "vid_type index update ran" during its runtime.

If this was restarted at any point during this restart, then the previous `startup_checks` flag would remain set. Then, because of the multithreading check that is performed, to ensure that more than one of them doesn't initiate the startup function, none of the threads ever start the process and clean it up.

This seems to be a common enough case that we might have to find another method for determining if a startup_check is active and if we can determine if a restart occurred in the middle of the last check. It might just have to be setting an expiration on the startup_check that is a certain time period less than the expectation for running (something along the lines of multiple hours, potentially), and then allowing that expiration to be overridden with the final call for 120 seconds. This will ensure that, at some point after this run, it can update.

Will discuss and determine a best action forward so we don't have to have users going in through Redis and manually deleting or expiring those keys.

**Comment by bbilly1** [comment]
Additionally as explained, the issue probably originated from a startup failure. You can apply the same step as here: https://github.com/tubearchivist/tubearchivist/issues/412#issuecomment-1399467568 to clear the startup lock, restart and monitor for any errors during startup.

Then obviously we need to come up with a better solution how to handle that in the future.

**Comment by Jay4242** [comment]
@lamusmaser great!  Thanks, I did have to run those commands to clear the locks apparently.  

Is there anything similar I need to do to rescan my filesystem?

I tried clicking 'Reindex' on a channel that's missing but it simply says "Reindex scheduled" since then.

**Comment by lamusmaser** [comment]
@Jay4242, as noted by @bbilly1, you will want to follow those directions and clear the startup_lock. Once that is clear, restart the TubeArchivist container and that will allow it to clear any other latent locks that are stopping tasks from being performed, such as the one noted.

**Comment by Jay4242** [comment]
Okay, I ended up clearing out anything that looked like it had to do with rescanning, reindexing, etc. and now it seems like I can Reindex the videos of channels to get the videos back into the UI.

Idk which key was still holding it up, but it's gone.

Thanks for the help.
