### ISSUE TITLE
[Bug]: Download queue breaks if issue with thumbnail

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#425]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

## Describe the bug
4000+ videos into a 4600+ extrac_dl task the below error killed the task and all previously "queued" videos were not added to the download queue

## Steps To Reproduce
Haven't been able to purposefully re-create

## Expected behavior
1. Default thumbnail added and move to next item in the queue
2. Even if error, not to loose all previously "queued" videos from task from being added to queue

### Relevant log output

```shell
[2023-02-05 05:19:49,231: WARNING/ForkPoolWorker-33] OZq0Hd-_4Kk (VideoTypeEnum.VIDEOS): add to download queue
[download] Got error: <urlopen error [Errno -3] Temporary failure in name resolution>
[download] Got error: <urlopen error [Errno -3] Temporary failure in name resolution>
[2023-02-05 05:24:07,577: WARNING/ForkPoolWorker-33] OZq0Hd-_4Kk: retry thumbnail download https://i.ytimg.com/vi/OZq0Hd-_4Kk/hqdefault.jpg
[2023-02-05 05:24:16,589: ERROR/ForkPoolWorker-33] Task home.tasks.extrac_dl[688e69e3-966b-4cd6-b33c-341adf2f7106] raised unexpected: AttributeError("'bool' object has no attribute 'size'")
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 151, in extrac_dl
    pending_handler.add_to_pending()
  File "/app/home/src/download/queue.py", line 227, in add_to_pending
    ThumbManager(youtube_id).download_video_thumb(url)
  File "/app/home/src/download/thumbnails.py", line 123, in download_video_thumb
    width, height = img_raw.size
AttributeError: 'bool' object has no attribute 'size'
```

**Comment by lamusmaser** [comment]
Looking at the code response, it looks like it went through this flow:
`download_video_thumb()` was called, it does its checks and confirms it needs to download. Reference: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/download/thumbnails.py#L122

This calls `download_raw()`. We have several `return` statements, and this _seems_ to be falling through to the final one, where it returns `False`. But before that, we can see that it finds the URL, skipping the first return catch. Then it does attempt to download, but we see the first attempt fail, since we get the printed output of `retry thumbnail download`, but that is the only time it comes through, so it doesn't finish the for-loop, nor does it seem to jump. Reference: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/download/thumbnails.py#L36-L58

Because it isn't finishing the for-loop, we know that it isn't going to the return at the end directly, unless it is failing out of the for-loop, which I'm not seeing a way for it do normally. That would mean that it should be jumping to `get_fallback()`, and it looks like we are getting it through the 404 status response code, since we don't have a printed `failed to open thumbnail` in the logs. Reference: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/download/thumbnails.py#L36-L58

`self.fallback` should be set to `False` by default, so we should skip the first check. The next thing I could think of is that it might have failed out looking up in the `default_map`, however that would have given a different error AND still would have attempted to return the image object. This means that the `Image.open()` call, at some point, is returning a `bool` response, instead, and that isn't being handled. Because it is happening before fatal error, we don't have details on the object; additionally, because this seems to be intermittent, it would be hard to determine which of the responses caused it.

Recommendation: Can we add a `print()` to denote when we are going into the `get_fallback()` method that would allow us to determine if that is coming through? Additionally, we could check the `img_raw` response in the `download_video_thumb()` method to try/catch that size attribute check, and cause a forced `get_fallback()` if that didn't succeed.

**Comment by bbilly1** [comment]
I think this is a bug in Pillow, obviously hard to reproduce, so I don't think it makes sense to raise this with them, because how could you explain that. From their documentation: `Image.open` returns an `Image` object, [[link](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open)], so that's also what TA expects. 

So I think we'll have to add another check if that really is an `Image` object, and return the fallback if not.

**Comment by bbilly1** [comment]
Thanks for reporting, v0.3.3 can now work around this bug and will use the fallback thumbnail.
