### ISSUE TITLE
[Feature Request]: Quick Add button

### ISSUE THREAD

**Issue by insuusvenerati** [tubearchivist/tubearchivist#452]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
No
## Describe the solution you'd like

As a user i'd like to be able to add, and immediately start downloading, a single video directly from the homepage or nav area.

## Additional context
Some of the logic may also be able to be reused to implement an Add + Immediately download a single video button on the Downloads page.

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by PhuriousGeorge** [comment]
+1 I think this might be easily achieved with the task refactoring I've heard rumblings about

**Comment by bbilly1** [comment]
I have been thinking about that as well, I've even added it to the [blocking list](https://github.com/tubearchivist/tubearchivist/issues/415) yesterday while refactoring the task backend. I think there are two parts to it:

**Backend**: The new refactored task backend will be able to send signals to a running worker task to stop or cancel a task. So this makes the whole task queue handling much more straight forward and we should be able to take the next item directly from ES instead of as it is implemented now, with a temporary queue in Redis. This would also fix the current limitation that new videos added to the queue while the queue is running won't get downloaded until you start the queue again.

So I was thinking to implement two additional fields in the ES download object: `auto` boolean field, these videos will get automatically downloaded when added. So there needs to be a check at the end of the *add to download queue* task to start the queue if needed. Second field `priority` integer, for additional sorting besides the *date added* timestamp.

This would allow for things like auto download your subscriptions, auto download ids send from the browser extension, prioritize your subscriptions over regular full channel downloads and more like that.

Then the `get_next` in the download queue loop would take the video directly from ES, with sorting and filtering applied as described above.

**Frontend**: I don't think we should make an additional form for that. Or at least I don't see how this could be done without duplicating functionality and cluttering up the UI. Also from a UX point of view, it makes sense to have download functionality on the download page. That probably needs a *autostart* checkbox in the download form and a config option on the settings page to add subscriptions as priority.

What do you think?

**Comment by bbilly1** [comment]
@insuusvenerati Any thoughts on that? I've merged the task backend refactor to the testing, there are still a few problems to solve before making an unstable build, but you could start work on that from here.

**Comment by bbilly1** [comment]
that's now implemented in v0.3.6.
