### ISSUE TITLE
[Installation]: removing `expose` ports in VPN setup

### ISSUE THREAD

**Issue by zero-thermo** [tubearchivist/tubearchivist#455]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux docker-compose

### Your installation or setup question

I'm running TubeArchivist behind a Gluetun VPN in two different docker-compose.yaml files. To get it to work, I had to do the following:

Used `localhost` to access the Elasticsearch and Redis containers instead of the container names. 
`ES_URL=http://localhost:9200`  
`REDIS_HOST=localhost`  

Assign `TA_PORT` to something other than `8000` to avoid any nginx bind problems.  

Added `network_mode: container:gluetun` to all three TubeArchivist services.  

**Removed the `expose` ports from the Elasticsearch and Redis services to allow for `network_mode` to be used.**  

Aside from the error messages in the logs, TubeArchivist seems to be working. What impact does removing the `expose` ports have on TubeArchivist, and is this causing the log errors? I can't get it to work with `expose` enabled.

Thanks for your time, and for working on this useful app.

### Relevant log output
I see this repeated error in the logs

```shell
invalid request block size: 21573 (max 8192)...skip
```

**Comment by zero-thermo** [comment]
Figured out what was causing the `invalid request block size` log errors. I needed to also change `TA_UWSGI_PORT` to resolve another conflict.

All that said, does removing `expose` have any impact on TubeArchivist? If not, why is it needed in the first place?

**Comment by bbilly1** [comment]
Refer to the docker compose specs for a detailed explanation of that distinction. 

But basically `ports` will publish the port to be accessible through the host network, this will also overwrite your firewall configurations. So you'll want to use that for services that you need to access over the host network. Then `expose` only makes the port available for containers on the same docker network. You'll usually want to use that for dependency containers that don't need to be accessed directly over the network. 

The example compose file assumes a standard configuration, but there are advanced options through additional env vars for things like VPN containers and the like. But that's beyond the scope of this project.

**Comment by zero-thermo** [comment]
I did not replace `expose` with `ports`, yet everything still works. Seems like the port is still available for containers on the same docker network even without `port` or `expose` settings.

Is this WAI for TubeArchivist, since the ports are still accessible even without `expose`? If so, then it doesn't seem like using `expose` or not makes any difference.

Appreciate your time and reply even though this is beyond the project scope.

**Comment by bbilly1** [comment]
Ultimately that depends on the actual service that is running inside the container. In the case of TA, nginx is running on port 8000, check the nginx config to confirm that, so nginx will publish that. If you don't specify a `ports` key on the service, you shouldn't be able to access that container from the host network, docker internally, they are still connected on a network by default, so they can talk to each other through that network and are resolvable through their service name as well as their IP.

You can install some network debugging tools like `ping`, `nmap` and `traceroute` in the container to play around to learn more. So `expose` is mostly for documenting how the services are running, as far as I know, that doesn't actually do anything. But because docker puts the containers on the same network by default, they can talk with each other.

**Comment by lamusmaser** [comment]
As long as the `expose` is described by either the `DOCKERFILE` or `docker-compose.yml`, the container will show the port as available. Since we build it as part of the `DOCKERFILE`, it will be available by default. It could be removed from each of the `docker-compose.yml` without impact, but this allows for some local description of what is expected to be available. This can be seen in the `docker ps` description for ports, as well. Ports that aren't forwarded will not have a left-hand reference in the definition.

**Comment by zero-thermo** [comment]
Thanks for the extra information. Learned a lot and will poke around with some of those network tools.
