### ISSUE TITLE
[Feature Request]: Keep video option

### ISSUE THREAD

**Issue by prouderthings** [tubearchivist/tubearchivist#486]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
No, not a problem per say.  I think it would be helpful to have a "keep video" option to prevent it from being auto-deleted.  I can not use the auto-delete feature because I would like to keep certain videos (i.e. music videos).

## Describe the solution you'd like
Add a "Keep Video" option that prevents auto-deletion.

## Additional context
Thank you for all you've done! This is a great project that fills a need for many!

### Your help is needed!

- [x] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
If you set the auto-delete to disabled, it accomplishes your goal. Is this the expected behavior that you are seeing?

**Comment by bbilly1** [comment]
Did you see, you can already do this on a per channel basis? Like only set these channels to autodelete that doesn't have videos you'll want to keep?

https://docs.tubearchivist.com/channels/#about

**Comment by prouderthings** [comment]
So I have most channels set to auto delete, but there are times were I wish I could keep one and delete the rest that come from the same channel. For example, my household enjoys a holiday episode on a channel and watch it frequently. I would love a feature that would allow me to mark the video as "do not delete",  but allow auto deletetion on other videos in the same channel. If this already exist, I have not been able to find it.

**Comment by SimonFischer04** [comment]
Hi, also would love a feature like this.
I already know about the override per channel, but is there also something similar per playlist? 
For example I have a private "music" playlist that I want to keep, but videos from my watch-later playlist should get deleted normally after some time (so per channel setting does not work for me)

Also, how is this handled currently? Do videos in playlists just count to the channel / get deleted according to channel settings /(global if nothing specified)?

**Comment by bbilly1** [comment]
Per playlist overwrite is probably not a good idea, as a video can be in multiple playlists at the same time, even in multiple playlists from multiple channels. So that can easily lead to confusing behavior, even more so with destructive actions like deleting videos. 

How this is handled currently is a video belongs to a channel, all logic is tied to the channel, playlist is just metadata. 

I suggest to take a similar approach as the channel overwrites, make a video overwrite. I'm sure we will come up with additional keys that we might want to add to that. 

My focus has always been doing things in bulk, not on a per video basis. If somebody wants to implement per video overwrite, feel free to open an PR. Reach out on Discord if you get stuck.

**Comment by danielyrovas** [comment]
Does TubeArchivist currently check if a video is in a playlist before deleting it? Or will the videos from a playlist be automatically deleted if they are watched and the channel is set to auto-delete watched?

**Comment by bbilly1** [comment]
Pruning stale issues. Somebody really wants to implement this, please go ahead. Focus will be on archiving functionality.
