### ISSUE TITLE
[Bug]: Files with capitalized extensions are not imported

### ISSUE THREAD

**Issue by naamval** [tubearchivist/tubearchivist#502]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
When doing a manual import, files that have a capitalized extension (like _.MP4_) are ignored.

## Steps To Reproduce
1. Have a file with a capitalized extension in the cache/import folder
2. Press 'manual import'
3. TubeArchivist reports that the task has completed successfully, without doing anything

### Relevant log output

```shell
(not applicable)
```

**Comment by lamusmaser** [comment]
It is handling it correctly, which is that it is looking for [specific extensions](https://github.com/tubearchivist/tubearchivist/blob/cd25eadd1c8752971cb139b42e7057b953ec3368/tubearchivist/home/src/index/manual.py#L34-L39), then skipping any files that don't match those extensions. Since `.MP4` is not in the extension list, that is getting skipped.

This could be handled very quickly with a simple modification to the [`_detect_type` function](https://github.com/tubearchivist/tubearchivist/blob/cd25eadd1c8752971cb139b42e7057b953ec3368/tubearchivist/home/src/index/manual.py#L117-L124). If we always pass the `ext` as lowercase in the comparison, specifically on [Line 121](https://github.com/tubearchivist/tubearchivist/blob/cd25eadd1c8752971cb139b42e7057b953ec3368/tubearchivist/home/src/index/manual.py#L121), then this should be easy to cover. This would then allow `.mp4` and `.MP4` to come through equivocally.

I'll make the PR and we'll get this included.
