### ISSUE TITLE
[Bug]: Does not import all videos

### ISSUE THREAD

**Issue by p6002** [tubearchivist/tubearchivist#503]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu Server on Proxmox VE

### Your Bug Report

The tool downloads only some of the videos from the added channels/playlists. 

Additionally, when I add playlist in the playlist tab, it adds the channel in the channel tab instead of the playlist. 

Unfortunately, the tool is useless due to the fact that it only downloads selected videos. Not suitable for backup, which is a shame, it would be useful before YT introduces paid FHD.

**Comment by p6002** [comment]
Hey. I simply started the container using docker compose, added a channel from which it only downloaded about 100 videos, where there are more than 200. 
This is a clean install, standard settings. 
There is no error, it just doesn't detect all the videos from the channel. 
Regarding the playlist tab it should be removed, since its only function is the + button, which can be moved to the channels tab, since the playlist is added there anyway. 

Oh and one more thing, the tool works only in the administrator group 1000:0, which is not very secure. A few months ago when I tested it, it was the same. There is no solution to this problem anywhere.

**Comment by lamusmaser** [comment]
1. This is covered by our [FAQ](https://docs.tubearchivist.com/faq/#why-does-subscribing-to-a-channel-not-download-the-complete-channel) and is determined by the [channel page size](https://docs.tubearchivist.com/settings/#subscriptions). If you wish to download a full channel, as it says, you can just add the channel URL to the download queue and it will pull the full channel. This is recommended for a first time subscription to a channel that is being backed up.
2. At least one setting has been changed, since the default for the `channel page size` is 50.
3. Covered by 1.
4. That is not its only function. Yes, we understand that playlist capabilities and features could be expanded upon, however those are in the [road-map](https://github.com/tubearchivist/tubearchivist#roadmap) for long-term development.
5. This should only be [required for ElasticSearch](https://github.com/tubearchivist/tubearchivist#permissions-for-elasticsearch). Otherwise, you can use [the HOST_UID and HOST_GID](https://github.com/tubearchivist/tubearchivist#installing) to supply an alternative UID/GID for TubeArchvist. There are some specific situations where these cannot be modified, such as NFS, however those are current edge-cases. One of the unlisted road-map items is to have better filesystem user integration, however that requires an overhaul on how we manage the filesystem currently and an integration with some other tooling, which hasn't yet been defined nor has it got an associated author to work on it.

Again, you are more than welcome to help contribute to the project, but this is something that we want to understand from either a critical point of view or providing enough evidence to show what the issues are. Almost everything was found fairly quickly within either the README or Docs, so it would probably be a good start to initially go from there. We are looking for people to help, whether that is in clarifying the README/Docs, providing PRs to resolve bugs/implement feature requests, or helping us with understanding the requirements for a particularly difficult feature request. This is still in a pre-1.0 release, and should be treated as such, with lots of room to grow and take into account some of these issues.

**Comment by PhuriousGeorge** [comment]
The functionality for what you're wanting is here.  If the docs can be made clearer, please make a suggestion or a pull in the doc repo.  I personally have 1907 channels fully backed-up and over 1 million videos all together in TA, so it does work (and other than scripts, the only YT-downloader that has been able to handle my hoard).

Regarding playlists, there are playlists for channels and there are playlists that are channel-agnostic.  Both have their uses and can be added in multiple ways, solving many use-cases.

There are things that can be better, clearer, etc. If you want change, please take part in positive conversation.
