### ISSUE TITLE
[Bug]: Migrate remaining docs to the documentation site.

### ISSUE THREAD

**Issue by dfarning** [tubearchivist/tubearchivist#593]
The title should be migrate remaining doc to the documentation site. Grammarly is really mangling the input boxes on github lately....

### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker on Ubuntu 22.04

## Describe the bug
https://github.com/tubearchivist/tubearchivist/blob/master/ARCHITECTURE.md
https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md

These two documentation files are still in the root directory of main tube archivist project.

## Expected behavior

I would expect that after the refactoring to the separate docs project, the contents of these two files would have been migrated. Just a bit confusing for someone trying to set up a dev env for the first time.

### Relevant log output

```shell
NA
```

### Anything else?

NA

**Comment by bbilly1** [comment]
CONTRIBUTING.md is defined by github and expected to be there in the root of the repo, that will also show up in the GH interface, that's mentioned in the github docs and should contain all guidelines for contributors:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

ARCHITECTURE.md is there because CONTRIBUTING.md is there. This way you only need to clone one repo to start to contribute this project, you have all self contained and not spread out.

Then docs.tubearchivist.com is mostly user documentation. 

That separation makes sense. Plus in any case, I don't want to change that to not break any links and by that making contributing to this repo harder that it needs to be.
