### ISSUE TITLE
[Installation]: Random names of downloaded files

### ISSUE THREAD

**Issue by p6002** [tubearchivist/tubearchivist#808]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Ubuntu Server, docker.

### Your installation or setup question

I haven't used Tubearchivist for half a year and now the names of the newly downloaded channels and files are wrong, how do I fix this?

![Zrzut ekranu 2024-09-5 o 15 06 52](https://github.com/user-attachments/assets/f1d3fce0-703f-4dac-a269-d855044ccca6)

### Relevant log output

```Shell
what log
```

**Comment by bbilly1** [comment]
https://docs.tubearchivist.com/faq/#why-is-there-no-flexible-naming-structure

**Comment by p6002** [comment]
Thanks, it make sense now.

**Comment by b-hayes** [comment]
I get it but not having useful filenames means you are forced to use special integrations instead of just saying, here's other files plex, your friend or whatever else might want to use them outside of TA.
Not sure why they wouldnt just use some metadata in a db to track what channel id etc matches the file so the files can be something useful.

**Comment by b-hayes** [comment]
@lamusmaser thanks for the reply.
Is there a way to supply my own file naming function or something to that effect that will allow TA to continue to function as normal with different file names?
