### ISSUE TITLE
Generate Open Telemetry compatible traces

### ISSUE THREAD

**Issue by insuusvenerati** [tubearchivist/tubearchivist#812]
Shouldn't be too difficult with Django :) 

Gonna look into it

**Comment by insuusvenerati** [comment]
https://uptrace.dev/get/instrument/opentelemetry-django.html

**Comment by bbilly1** [comment]
I don't want to build in telemetry to this project. Maybe at some point we'll standardize the logs, so that could be used in some kind of log aggregation software, but that would be outside of this project, directly through docker logs. 

But we currently have our hands full with the react frontend situation.
